# Generated by Django 4.0.4 on 2022-04-21 23:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MassageModel',
            new_name='MessageModel',
        ),
    ]
