# Generated by Django 4.0.4 on 2022-04-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_massagemodel_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='room',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
