# Generated by Django 4.0.4 on 2022-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messagemodel_chang_messagemodel_seen_roommodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='last_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='seen',
            field=models.IntegerField(null=True),
        ),
    ]
