# Generated by Django 4.0.4 on 2022-05-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_roommodel_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='seen',
            field=models.IntegerField(null=True),
        ),
    ]
