# Generated by Django 4.0.4 on 2022-05-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_roommodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
