# Generated by Django 4.0.4 on 2022-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_roommodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='seen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
